### ISSUE TITLE
Cancel Override --> save

### ISSUE THREAD

**Issue by Mino-2024** [MechatronikMonkey/SatisfactorySync#2]
Cancel warning Dialog with X (top right Corner) --> Upload startest

X should cancel Upload

**Comment by MechatronikMonkey** [comment]
Behavior could not be reproduced on Windows 11 system. 
What exact warning dialog?
Could you provide screenshot or describe in detail please?

**Comment by MechatronikMonkey** [comment]
Should be fixed. Test and if not fixed, re open the issue.
